/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.miwashi.crud;

import org.junit.jupiter.api.Test;
import org.testcontainers.containers.MySQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import static org.junit.jupiter.api.Assertions.*;


@Testcontainers
public class AppTest {

    @Container
    private static MySQLContainer mySQLContainer = new MySQLContainer("mysql:latest");

    @Test
    void shouldRun() {

        System.out.println(mySQLContainer.getJdbcUrl());
        System.out.println(mySQLContainer.getPassword());
        System.out.println(mySQLContainer.getDatabaseName());

    }
}
